### ISSUE TITLE
Limit book folder name length to something Windows can manage [Cat Knight]

### ISSUE THREAD

**Issue by RobbWatershed** [RobbWatershed/Hentoid#53]
Suick question, is there a way to check the size of the name of the folder that the books gets?

When I use the command to copy the folders from the app folder (adb) some books have humongous names that are bigger than windows can handle, and that results in the copy command failing and stopping instead of being able to finish

What I do in those cases is manually find the book folder copy the name to a txt inside the folder and then shorten the folder name to something windows/the command can actually copy/make a folder in the pc

I know which book is the one with the huge fold name because when it stops it shows what it was copying/moving so I have the full name of the folder and can search later

Don't know if you have any opinions or ideais about it, not really a problem just food for thoughts

**Comment by wightwulf1944** [comment]
I believe the folder name length limit depends on the underlying file system, and the operating system running it. If we are to assume NTFS and Windows, then the fully qualified file, with it's drivename, path, filename, and extension, altogether is limited to 260 characters.

This isn't something we can completely fix on our side because we don't know where the user might place their collection in their system. But we can try to mitigate it by packaging the collection into a single zip, or instructing the user to do so.

cite: https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista#265782

**Comment by RobbWatershed** [comment]
Done in da802c9d078208fb76a9e23bc1ff7763282caf74

**Comment by RobbWatershed** [comment]
truncating is not working, i tried selecting both 160 and 200 and it resulted in the name folder name and also both folder had the same name with a length of 278

deep_valley - Inkou_Kyoushi_no_Saimin_Seikatsu_Shidouroku_Sensei...Kare_no_Tame_ni_Watashi_no_Shojomaku__Kantsuu_ShiteKudasai - [246450]
 that's all in the same line but even discord can't handle deep valley names lol
